'use client';

import { useState, useCallback } from 'react';
import { UrlInput } from '@/components/ui/UrlInput';
import { LanguageSelector } from '@/components/ui/LanguageSelector';
import { LoadingSpinner } from '@/components/ui/LoadingSpinner';
import { TranscriptViewer } from '@/components/transcript/TranscriptViewer';
import { ViralClips } from '@/components/viral-clips/ViralClips';
import type {
  AppStatus,
  LanguageInfo,
  TranscriptSegment,
  ListLanguagesResponse,
  FetchTranscriptResponse,
  ErrorResponse,
} from '@/lib/types';
import styles from './page.module.css';

export default function HomePage() {
  const [status, setStatus] = useState<AppStatus>('idle');
  const [errorMessage, setErrorMessage] = useState<string>('');
  const [currentUrl, setCurrentUrl] = useState<string>('');
  const [currentVideoId, setCurrentVideoId] = useState<string>('');
  const [languages, setLanguages] = useState<LanguageInfo[]>([]);
  const [selectedLang, setSelectedLang] = useState<string | null>(null);
  const [segments, setSegments] = useState<TranscriptSegment[]>([]);
  const [confirmedLang, setConfirmedLang] = useState<string>('');

  const handleUrlSubmit = useCallback(async (url: string) => {
    setStatus('loading-languages');
    setErrorMessage('');
    setCurrentUrl(url);
    setLanguages([]);
    setSelectedLang(null);
    setSegments([]);

    try {
      const res = await fetch(`/api/languages?url=${encodeURIComponent(url)}`);
      const data: ListLanguagesResponse | ErrorResponse = await res.json();

      if (!data.success) {
        setErrorMessage((data as ErrorResponse).error);
        setStatus('error');
        return;
      }

      const response = data as ListLanguagesResponse;
      setCurrentVideoId(response.videoId);
      setLanguages(response.languages);
      // Pre-select the first auto-generated or first language
      const firstAuto = response.languages.find((l) => l.isAutoGenerated);
      setSelectedLang(firstAuto?.languageCode ?? response.languages[0]?.languageCode ?? null);
      setStatus('language-selection');
    } catch {
      setErrorMessage('Network error. Please check your connection and try again.');
      setStatus('error');
    }
  }, []);

  const handleConfirmLanguage = useCallback(async () => {
    if (!selectedLang) return;
    setStatus('loading-transcript');
    setErrorMessage('');

    try {
      const params = new URLSearchParams({ url: currentUrl, lang: selectedLang });
      const res = await fetch(`/api/transcript?${params.toString()}`);
      const data: FetchTranscriptResponse | ErrorResponse = await res.json();

      if (!data.success) {
        setErrorMessage((data as ErrorResponse).error);
        setStatus('error');
        return;
      }

      const response = data as FetchTranscriptResponse;
      setSegments(response.segments);
      setConfirmedLang(selectedLang);
      setStatus('ready');
    } catch {
      setErrorMessage('Network error. Please check your connection and try again.');
      setStatus('error');
    }
  }, [selectedLang, currentUrl]);

  function handleReset() {
    setStatus('idle');
    setErrorMessage('');
    setCurrentUrl('');
    setCurrentVideoId('');
    setLanguages([]);
    setSelectedLang(null);
    setSegments([]);
    setConfirmedLang('');
  }

  const isInputLoading = status === 'loading-languages';
  const isTranscriptLoading = status === 'loading-transcript';

  return (
    <main className={styles.main}>
      {/* Background effects */}
      <div className={styles.bgOrb1} aria-hidden="true" />
      <div className={styles.bgOrb2} aria-hidden="true" />
      <div className={styles.bgGrid} aria-hidden="true" />

      <div className={styles.content}>
        {/* Header */}
        <header className={styles.header}>
          <div className={styles.logoMark} aria-hidden="true">
            <svg width="28" height="28" viewBox="0 0 24 24" fill="none">
              <path d="M12 2L2 7l10 5 10-5-10-5z" fill="url(#g1)" opacity="0.9" />
              <path d="M2 17l10 5 10-5" stroke="url(#g2)" strokeWidth="2" strokeLinecap="round" />
              <path d="M2 12l10 5 10-5" stroke="url(#g3)" strokeWidth="2" strokeLinecap="round" />
              <defs>
                <linearGradient id="g1" x1="2" y1="7" x2="22" y2="12" gradientUnits="userSpaceOnUse">
                  <stop stopColor="#8b5cf6" />
                  <stop offset="1" stopColor="#3b82f6" />
                </linearGradient>
                <linearGradient id="g2" x1="2" y1="17" x2="22" y2="22" gradientUnits="userSpaceOnUse">
                  <stop stopColor="#8b5cf6" />
                  <stop offset="1" stopColor="#3b82f6" />
                </linearGradient>
                <linearGradient id="g3" x1="2" y1="12" x2="22" y2="17" gradientUnits="userSpaceOnUse">
                  <stop stopColor="#8b5cf6" />
                  <stop offset="1" stopColor="#3b82f6" />
                </linearGradient>
              </defs>
            </svg>
          </div>
          <div>
            <h1 className={styles.title}>
              <span className={styles.titleGradient}>YouTube Viral Clipper</span>
            </h1>
            <p className={styles.subtitle}>
              Extract transcripts from any YouTube video instantly and analyze viral clips
            </p>
          </div>
        </header>

        {/* Input card — always visible */}
        <section className={styles.inputCard} aria-label="YouTube URL input">
          <div className={styles.inputCardInner}>
            <UrlInput onSubmit={handleUrlSubmit} isLoading={isInputLoading} />
          </div>
          {status !== 'idle' && (
            <button
              id="reset-btn"
              className={styles.resetBtn}
              onClick={handleReset}
              aria-label="Start over"
            >
              <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <polyline points="1 4 1 10 7 10" />
                <path d="M3.51 15a9 9 0 1 0 .49-3.48" />
              </svg>
              Start over
            </button>
          )}
        </section>

        {/* Step areas */}
        <div className={styles.stepArea}>
          {/* Loading languages */}
          {status === 'loading-languages' && (
            <div className={`${styles.stateCard} ${styles.loadingCard}`}>
              <LoadingSpinner size="lg" label="Fetching available languages..." />
            </div>
          )}

          {/* Language selection */}
          {status === 'language-selection' && (
            <div className={styles.stateCard}>
              <LanguageSelector
                languages={languages}
                selected={selectedLang}
                onSelect={setSelectedLang}
                onConfirm={handleConfirmLanguage}
                isLoading={isTranscriptLoading}
              />
            </div>
          )}

          {/* Loading transcript */}
          {status === 'loading-transcript' && (
            <div className={`${styles.stateCard} ${styles.loadingCard}`}>
              <LoadingSpinner size="lg" label="Generating transcript..." />
              <p className={styles.loadingHint}>This may take a moment for longer videos</p>
            </div>
          )}

          {/* Error state */}
          {status === 'error' && (
            <div className={`${styles.stateCard} ${styles.errorCard}`} role="alert">
              <div className={styles.errorIcon} aria-hidden="true">
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <circle cx="12" cy="12" r="10" />
                  <line x1="12" y1="8" x2="12" y2="12" />
                  <line x1="12" y1="16" x2="12.01" y2="16" />
                </svg>
              </div>
              <div>
                <p className={styles.errorTitle}>Something went wrong</p>
                <p className={styles.errorMessage}>{errorMessage}</p>
              </div>
              <button
                id="retry-btn"
                className={styles.retryBtn}
                onClick={handleReset}
              >
                Try again
              </button>
            </div>
          )}

          {/* Transcript ready */}
          {status === 'ready' && segments.length > 0 && (
            <>
              <TranscriptViewer
                videoId={currentVideoId}
                segments={segments}
                languageCode={confirmedLang}
              />
              <ViralClips segments={segments} />
            </>
          )}
        </div>

        {/* Idle hero hints */}
        {status === 'idle' && (
          <div className={styles.hintSection} aria-label="Usage hints">
            <div className={styles.hintGrid}>
              {[
                {
                  icon: (
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <path d="M22.54 6.42a2.78 2.78 0 0 0-1.95-1.96C18.88 4 12 4 12 4s-6.88 0-8.59.46a2.78 2.78 0 0 0-1.95 1.96A29 29 0 0 0 1 12a29 29 0 0 0 .46 5.58A2.78 2.78 0 0 0 3.41 19.6C5.12 20 12 20 12 20s6.88 0 8.59-.46a2.78 2.78 0 0 0 1.95-1.95A29 29 0 0 0 23 12a29 29 0 0 0-.46-5.58z" />
                      <polygon points="9.75 15.02 15.5 12 9.75 8.98 9.75 15.02" />
                    </svg>
                  ),
                  title: 'Paste any YouTube URL',
                  desc: 'Supports full URLs, shortened links, and video IDs',
                },
                {
                  icon: (
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <circle cx="12" cy="12" r="10" />
                      <line x1="2" y1="12" x2="22" y2="12" />
                      <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
                    </svg>
                  ),
                  title: 'Choose your language',
                  desc: 'Pick from all available captions, including auto-generated ones',
                },
                {
                  icon: (
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                      <polyline points="22 12 18 12 15 21 9 3 6 12 2 12" />
                    </svg>
                  ),
                  title: 'Interactive viewer',
                  desc: 'Click any line to jump to that moment in the video',
                },
              ].map((hint, i) => (
                <div key={i} className={styles.hintCard}>
                  <div className={styles.hintIcon}>{hint.icon}</div>
                  <div>
                    <p className={styles.hintTitle}>{hint.title}</p>
                    <p className={styles.hintDesc}>{hint.desc}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>
    </main>
  );
}
