'use client';

import type { LanguageInfo } from '@/lib/types';

interface LanguageSelectorProps {
  languages: LanguageInfo[];
  selected: string | null;
  onSelect: (code: string) => void;
  onConfirm: () => void;
  isLoading: boolean;
}

export function LanguageSelector({
  languages,
  selected,
  onSelect,
  onConfirm,
  isLoading,
}: LanguageSelectorProps) {
  // Sort: auto-generated first, then alphabetical by name
  const sorted = [...languages].sort((a, b) => {
    if (a.isAutoGenerated !== b.isAutoGenerated) return a.isAutoGenerated ? -1 : 1;
    return a.languageName.localeCompare(b.languageName);
  });

  return (
    <div className="lang-selector-container">
      <div className="lang-selector-header">
        <div className="lang-selector-header-icon">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
            <circle cx="12" cy="12" r="10" />
            <line x1="2" y1="12" x2="22" y2="12" />
            <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
          </svg>
        </div>
        <div>
          <h3 className="lang-selector-title">Select Transcript Language</h3>
          <p className="lang-selector-subtitle">{languages.length} language{languages.length !== 1 ? 's' : ''} available</p>
        </div>
      </div>

      <div className="lang-selector-grid" role="listbox" aria-label="Available transcript languages">
        {sorted.map((lang) => (
          <button
            key={`${lang.languageCode}-${lang.isAutoGenerated ? 'auto' : 'manual'}`}
            role="option"
            aria-selected={selected === lang.languageCode}
            className={`lang-selector-btn ${selected === lang.languageCode ? 'lang-selector-btn-selected' : ''}`}
            onClick={() => onSelect(lang.languageCode)}
            id={`lang-option-${lang.languageCode}`}
          >
            <span className="lang-selector-name">{lang.languageName}</span>
            <span className="lang-selector-code">{lang.languageCode}</span>
            {lang.isAutoGenerated && (
              <span className="lang-selector-auto-badge">
                <svg width="10" height="10" viewBox="0 0 24 24" fill="currentColor">
                  <path d="M12 2a10 10 0 1 0 0 20A10 10 0 0 0 12 2zm1 15h-2v-2h2v2zm0-4h-2V7h2v6z" />
                </svg>
                Auto
              </span>
            )}
            {selected === lang.languageCode && (
              <span className="lang-selector-checkmark">
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round">
                  <polyline points="20 6 9 17 4 12" />
                </svg>
              </span>
            )}
          </button>
        ))}
      </div>

      <div className="lang-selector-footer">
        <button
          id="confirm-language-btn"
          className="lang-selector-confirm-btn"
          onClick={onConfirm}
          disabled={!selected || isLoading}
        >
          {isLoading ? (
            <span className="lang-selector-loading-dots">
              <span /><span /><span />
            </span>
          ) : (
            <>
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M12 20h9" /><path d="M16.5 3.5a2.121 2.121 0 0 1 3 3L7 19l-4 1 1-4L16.5 3.5z" />
              </svg>
              Generate Transcript
            </>
          )}
        </button>
      </div>
    </div>
  );
}
