// Transcript segment from youtube-transcript-plus
export interface TranscriptSegment {
  text: string;
  offset: number; // seconds (float) — as returned by youtube-transcript-plus
  duration: number; // seconds (float)
  lang?: string | null;
}

// Available language info
export interface LanguageInfo {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
}

// API response for language listing
export interface ListLanguagesResponse {
  success: true;
  videoId: string;
  languages: LanguageInfo[];
}

// API response for transcript fetching
export interface FetchTranscriptResponse {
  success: true;
  videoId: string;
  languageCode: string;
  segments: TranscriptSegment[];
}

// Generic error response
export interface ErrorResponse {
  success: false;
  error: string;
}


// ─── Viral Clip Analysis ───────────────────────────────────────────────────

export type ViralCategory =
  | 'HOOK'
  | 'EMOTIONAL_PEAK'
  | 'OPINION_BOMB'
  | 'REVELATION'
  | 'CONFLICT'
  | 'QUOTABLE_LINE'
  | 'STORY_PEAK'
  | 'PRACTICAL_VALUE';

export interface ViralClip {
  rank: number;
  viral_score: number;        // 0–100
  start_time: string;         // "MM:SS"
  end_time: string;           // "MM:SS"
  duration_seconds: number;
  title: string;
  hook: string;
  summary: string;
  why_viral: string;
  category: ViralCategory[];
  strengths: string[];
  weaknesses: string[];
}

export interface ViralAnalysisResult {
  overall_summary: string;
  clips: ViralClip[];
}

// API request/response
export interface AnalyzeRequest {
  transcript: string; // formatted as "[MM:SS] text\n..."
}

export interface AnalyzeSuccessResponse {
  success: true;
  result: ViralAnalysisResult;
}

export type AnalyzeResponse = AnalyzeSuccessResponse | ErrorResponse;

export interface YoutubeVideoMetadata {
  title: string;
  duration_string: string;
  duration_number: number;
  thumbnail: string;
  channel: string;
  description?: string;
}


export interface JobInfo {
  id: string;
  type: string;
  status: string;
  progress: number;
  error: string | null;
  payload?: unknown;
  createdAt: Date | string;
  completedAt: Date | string | null;
}

export interface ClipInfo {
  id: string;
  rank: number;
  viralScore: number;
  durationSeconds: number;
  startTime: string;
  endTime: string;
  processingStatus: string;
  processingError: string | null;
  title: string;
  category: string[];
  hook: string;
  summary: string;
  whyViral: string;
  strengths: string[];
  weaknesses: string[];
  asset: { id: string; storagePath: string } | null;
  subtitles: { id: string; format: string }[];
  faceDetections?: { id: string }[];
  hasVertical?: boolean;
  hasVerticalSubtitled?: boolean;
}

export interface VideoInfo {
  id: string;
  youtubeId: string;
  youtubeUrl: string;
  title: string | null;
  description: string | null;
  thumbnailUrl: string | null;
  duration: number | null;
  projectId: string;
  project: {
    id: string;
    name: string;
  };
  transcript: {
    id: string;
    languageCode: string;
    segments: TranscriptSegment[];
  } | null;
  viralAnalysis: {
    id: string;
    overallSummary: string | null;
    clips: ClipInfo[];
  } | null;
  jobs: JobInfo[];
}