// Transcript segment from youtube-transcript-plus
export interface TranscriptSegment {
  text: string;
  offset: number; // seconds (float) — as returned by youtube-transcript-plus
  duration: number; // seconds (float)
  lang?: string;
}

// Available language info
export interface LanguageInfo {
  languageCode: string;
  languageName: string;
  isAutoGenerated: boolean;
}

// API response for language listing
export interface ListLanguagesResponse {
  success: true;
  videoId: string;
  languages: LanguageInfo[];
}

// API response for transcript fetching
export interface FetchTranscriptResponse {
  success: true;
  videoId: string;
  languageCode: string;
  segments: TranscriptSegment[];
}

// Generic error response
export interface ErrorResponse {
  success: false;
  error: string;
}

export type ApiResponse<T> = T | ErrorResponse;

// App UI state
export type AppStatus =
  | 'idle'
  | 'loading-languages'
  | 'language-selection'
  | 'loading-transcript'
  | 'ready'
  | 'error';

// ─── Viral Clip Analysis ───────────────────────────────────────────────────

export type ViralCategory =
  | 'HOOK'
  | 'EMOTIONAL_PEAK'
  | 'OPINION_BOMB'
  | 'REVELATION'
  | 'CONFLICT'
  | 'QUOTABLE_LINE'
  | 'STORY_PEAK'
  | 'PRACTICAL_VALUE';

export interface ViralClip {
  rank: number;
  viral_score: number;        // 0–100
  start_time: string;         // "MM:SS"
  end_time: string;           // "MM:SS"
  duration_seconds: number;
  title: string;
  hook: string;
  summary: string;
  why_viral: string;
  category: ViralCategory[];
  strengths: string[];
  weaknesses: string[];
}

export interface ViralAnalysisResult {
  overall_summary: string;
  clips: ViralClip[];
}

// API request/response
export interface AnalyzeRequest {
  transcript: string; // formatted as "[MM:SS] text\n..."
}

export interface AnalyzeSuccessResponse {
  success: true;
  result: ViralAnalysisResult;
}

export type AnalyzeResponse = AnalyzeSuccessResponse | ErrorResponse;
