'use client';

import { useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { LanguageSelector } from '@/components/ui/LanguageSelector';
import type { LanguageInfo } from '@/lib/types';

interface TranscriptFetcherProps {
  videoId: string;
  hasTranscript: boolean;
}

type Step = 'idle' | 'loading-languages' | 'language-selection' | 'loading-transcript';

export function TranscriptFetcher({ videoId, hasTranscript }: TranscriptFetcherProps) {
  const router = useRouter();
  const [step, setStep] = useState<Step>('idle');
  const [error, setError] = useState('');
  const [languages, setLanguages] = useState<LanguageInfo[]>([]);
  const [selectedLang, setSelectedLang] = useState<string | null>(null);

  // Step 1: fetch available languages
  const handleFetchLanguages = useCallback(async () => {
    setStep('loading-languages');
    setError('');
    setLanguages([]);
    setSelectedLang(null);

    try {
      const res = await fetch(`/api/videos/${videoId}/languages`);
      const data = await res.json();
      if (!data.success) {
        setError(data.error ?? 'Failed to fetch available languages.');
        setStep('idle');
        return;
      }
      const langs: LanguageInfo[] = data.languages;
      setLanguages(langs);
      // Pre-select first auto-generated or first language
      const firstAuto = langs.find((l) => l.isAutoGenerated);
      setSelectedLang(firstAuto?.languageCode ?? langs[0]?.languageCode ?? null);
      setStep('language-selection');
    } catch {
      setError('Network error.');
      setStep('idle');
    }
  }, [videoId]);

  // Step 2: fetch transcript with chosen language
  const handleConfirmLanguage = useCallback(async () => {
    if (!selectedLang) return;
    setStep('loading-transcript');
    setError('');

    try {
      const params = new URLSearchParams();
      params.set('lang', selectedLang);
      const res = await fetch(`/api/videos/${videoId}/transcript?${params.toString()}`);
      const data = await res.json();
      if (!data.success) {
        setError(data.error ?? 'Failed to fetch transcript.');
        setStep('language-selection');
        return;
      }
      router.refresh();
      setStep('idle');
    } catch {
      setError('Network error.');
      setStep('language-selection');
    }
  }, [videoId, selectedLang, router]);

  const handleCancel = useCallback(() => {
    setStep('idle');
    setError('');
    setLanguages([]);
    setSelectedLang(null);
  }, []);

  return (
    <div className="transcript-fetcher">
      {/* Initial trigger button */}
      {step === 'idle' && (
        <div className="transcript-fetcher-row">
          <button
            id="fetch-transcript-btn"
            onClick={handleFetchLanguages}
            className="form-submit-btn"
          >
            {hasTranscript ? 'Re-fetch Transcript' : 'Fetch Transcript'}
          </button>
        </div>
      )}

      {/* Loading languages */}
      {step === 'loading-languages' && (
        <div className="transcript-fetcher-row">
          <span className="transcript-fetcher-status">Fetching available languages…</span>
        </div>
      )}

      {/* Language selection */}
      {step === 'language-selection' && (
        <div className="transcript-fetcher-lang-selection">
          <LanguageSelector
            languages={languages}
            selected={selectedLang}
            onSelect={setSelectedLang}
            onConfirm={handleConfirmLanguage}
            isLoading={false}
          />
          <button
            id="cancel-language-selection-btn"
            onClick={handleCancel}
            className="form-cancel-btn"
          >
            Cancel
          </button>
        </div>
      )}

      {/* Loading transcript */}
      {step === 'loading-transcript' && (
        <div className="transcript-fetcher-row">
          <span className="transcript-fetcher-status">Fetching transcript…</span>
        </div>
      )}

      {error && <p className="form-error">{error}</p>}
    </div>
  );
}
