'use client';

import { useState, useCallback } from 'react';
import { useRouter } from 'next/navigation';
import { LanguageSelector } from '@/components/ui/LanguageSelector';
import { TranscriptViewer } from '@/components/transcript/TranscriptViewer';
import type { LanguageInfo, TranscriptSegment } from '@/lib/types';

interface VideoTranscriptSectionProps {
  videoId: string;           // DB id
  youtubeId: string;
  initialSegments: TranscriptSegment[];
  initialLanguageCode: string;
}

type Step = 'idle' | 'loading-languages' | 'language-selection' | 'loading-transcript';

export function VideoTranscriptSection({
  videoId,
  youtubeId,
  initialSegments,
  initialLanguageCode,
}: VideoTranscriptSectionProps) {
  const router = useRouter();

  const [step, setStep] = useState<Step>('idle');
  const [error, setError] = useState('');
  const [languages, setLanguages] = useState<LanguageInfo[]>([]);
  const [selectedLang, setSelectedLang] = useState<string | null>(null);

  const hasTranscript = initialSegments.length > 0;

  // Step 1: Fetch available languages
  const handleFetchLanguages = useCallback(async () => {
    setStep('loading-languages');
    setError('');
    setLanguages([]);
    setSelectedLang(null);

    try {
      const res = await fetch(`/api/videos/${videoId}/languages`);
      const data = await res.json();

      if (!data.success) {
        setError(data.error ?? 'Failed to fetch available languages.');
        setStep('idle');
        return;
      }

      const langs: LanguageInfo[] = data.languages;
      setLanguages(langs);

      // Pre-select first auto-generated or first language
      const firstAuto = langs.find((l) => l.isAutoGenerated);
      setSelectedLang(firstAuto?.languageCode ?? langs[0]?.languageCode ?? null);
      setStep('language-selection');
    } catch {
      setError('Network error.');
      setStep('idle');
    }
  }, [videoId]);

  // Step 2: Fetch transcript with chosen language
  const handleConfirmLanguage = useCallback(async () => {
    if (!selectedLang) return;
    setStep('loading-transcript');
    setError('');

    try {
      const params = new URLSearchParams({ lang: selectedLang });
      const res = await fetch(`/api/videos/${videoId}/transcript?${params.toString()}`);
      const data = await res.json();

      if (!data.success) {
        setError(data.error ?? 'Failed to fetch transcript.');
        setStep('language-selection');
        return;
      }

      // Refresh server data and go back to idle to show new transcript
      router.refresh();
      setStep('idle');
    } catch {
      setError('Network error.');
      setStep('language-selection');
    }
  }, [videoId, selectedLang, router]);

  const handleCancel = useCallback(() => {
    setStep('idle');
    setError('');
    setLanguages([]);
    setSelectedLang(null);
  }, []);

  const isBusy = step === 'loading-languages' || step === 'loading-transcript';

  return (
    <section className="dash-section">
      {/* ── Section header ── */}
      <div className="dash-section-header">
        <h2 className="dash-section-title">
          Video &amp; Transcript
          {hasTranscript && step === 'idle' && (
            <span className="badge badge-success ml-2">
              {initialSegments.length} segments
            </span>
          )}
        </h2>

        {/* Fetch / Re-fetch button — only visible when idle */}
        {step === 'idle' && (
          <button
            id="fetch-transcript-btn"
            onClick={handleFetchLanguages}
            className="form-submit-btn"
          >
            {hasTranscript ? 'Re-fetch Transcript' : 'Fetch Transcript'}
          </button>
        )}
      </div>

      {/* ── Loading languages ── */}
      {step === 'loading-languages' && (
        <p className="transcript-fetcher-status">Fetching available languages…</p>
      )}

      {/* ── Language selection ── */}
      {step === 'language-selection' && (
        <div className="transcript-fetcher-lang-selection">
          <LanguageSelector
            languages={languages}
            selected={selectedLang}
            onSelect={setSelectedLang}
            onConfirm={handleConfirmLanguage}
            isLoading={false}
          />
          <button
            id="cancel-language-selection-btn"
            onClick={handleCancel}
            className="form-cancel-btn"
          >
            Cancel
          </button>
        </div>
      )}

      {/* ── Loading transcript ── */}
      {step === 'loading-transcript' && (
        <p className="transcript-fetcher-status">Fetching transcript…</p>
      )}

      {/* ── Error ── */}
      {error && <p className="form-error">{error}</p>}

      {/* ── Transcript viewer — hidden while language selection is active ── */}
      {hasTranscript && !isBusy && step !== 'language-selection' && (
        <TranscriptViewer
          videoId={youtubeId}
          segments={initialSegments}
          languageCode={initialLanguageCode}
        />
      )}
    </section>
  );
}
