'use client';

import { useState, useCallback, useMemo } from 'react';
import { LanguageSelector } from '@/components/transcript/LanguageSelector';
import { TranscriptViewer } from '@/components/transcript/TranscriptViewer';
import type { LanguageInfo, TranscriptSegment } from '@/lib/types';

interface VideoTranscriptSectionProps {
  videoId: string;           // DB id
  youtubeId: string;
  initialSegments: TranscriptSegment[];
  initialLanguageCode: string;
  onTranscriptUpdated?: (segments: TranscriptSegment[], lang: string) => void;
}

type Step = 'idle' | 'loading-languages' | 'language-selection' | 'loading-transcript';

export function VideoTranscriptSection({
  videoId,
  youtubeId,
  initialSegments,
  initialLanguageCode,
  onTranscriptUpdated,
}: VideoTranscriptSectionProps) {

  const [step, setStep] = useState<Step>('idle');
  const [error, setError] = useState('');
  const [languages, setLanguages] = useState<LanguageInfo[]>([]);
  const [selectedLang, setSelectedLang] = useState<string | null>(null);
  const [prevInitialSegments, setPrevInitialSegments] = useState(initialSegments);
  const [prevInitialLang, setPrevInitialLang] = useState(initialLanguageCode);
  const [currentSegments, setCurrentSegments] = useState<TranscriptSegment[]>(initialSegments);
  const [currentLanguageCode, setCurrentLanguageCode] = useState<string>(initialLanguageCode);

  if (initialSegments !== prevInitialSegments) {
    setPrevInitialSegments(initialSegments);
    setCurrentSegments(initialSegments);
  }

  if (initialLanguageCode !== prevInitialLang) {
    setPrevInitialLang(initialLanguageCode);
    setCurrentLanguageCode(initialLanguageCode);
  }

  const hasTranscript = currentSegments.length > 0;

  const selectedLangLabel = useMemo(() => {
    if (!selectedLang) return null;
    const found = languages.find((l) => l.languageCode === selectedLang);
    if (!found) return selectedLang.toUpperCase();
    return `${found.languageName}${found.isAutoGenerated ? ' (Auto)' : ''}`;
  }, [languages, selectedLang]);

  // Step 1: Fetch available languages
  const handleFetchLanguages = useCallback(async () => {
    setStep('loading-languages');
    setError('');
    setLanguages([]);
    setSelectedLang(null);

    try {
      const res = await fetch(`/api/videos/${videoId}/languages`);
      const data = await res.json();

      if (!data.success) {
        setError(data.error ?? 'Failed to fetch available languages.');
        setStep('idle');
        return;
      }

      const langs: LanguageInfo[] = data.languages;
      setLanguages(langs);

      // Pre-select first auto-generated or first language
      const firstAuto = langs.find((l) => l.isAutoGenerated);
      setSelectedLang(firstAuto?.languageCode ?? langs[0]?.languageCode ?? null);
      setStep('language-selection');
    } catch {
      setError('Network error. Unable to retrieve transcript languages.');
      setStep('idle');
    }
  }, [videoId]);

  // Step 2: Fetch transcript with chosen language
  const handleConfirmLanguage = useCallback(async () => {
    if (!selectedLang) return;
    setStep('loading-transcript');
    setError('');

    try {
      const params = new URLSearchParams({ lang: selectedLang });
      const res = await fetch(`/api/videos/${videoId}/transcript?${params.toString()}`);
      const data = await res.json();

      if (!data.success) {
        setError(data.error ?? 'Failed to fetch transcript.');
        setStep('language-selection');
        return;
      }

      if (Array.isArray(data.segments)) {
        setCurrentSegments(data.segments);
        const newLang = data.languageCode || selectedLang || '';
        setCurrentLanguageCode(newLang);
        onTranscriptUpdated?.(data.segments, newLang);
      }

      setStep('idle');
    } catch {
      setError('Network error. Unable to fetch video transcript.');
      setStep('language-selection');
    }
  }, [videoId, selectedLang, onTranscriptUpdated]);

  const handleCancel = useCallback(() => {
    setStep('idle');
    setError('');
    setLanguages([]);
    setSelectedLang(null);
  }, []);

  const isBusy = step === 'loading-languages' || step === 'loading-transcript';

  return (
    <section className="dash-section">
      <div className="vts-container">
        {/* ── Section header ── */}
        <div className="dash-section-header">
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', flexWrap: 'wrap' }}>
            <h2 className="dash-section-title" style={{ margin: 0 }}>
              Video &amp; Transcript
            </h2>
            {hasTranscript && step === 'idle' && (
              <span className="vts-header-badge">
                <span className="vts-header-badge-dot" />
                {currentSegments.length} segments ({currentLanguageCode.toUpperCase()})
              </span>
            )}
          </div>

          {/* Action button */}
          <div>
            {step === 'loading-languages' ? (
              <button className="vts-fetch-btn" disabled>
                <span className="auth-spinner" style={{ width: '13px', height: '13px', borderWidth: '2px' }} aria-hidden="true" />
                Fetching Languages…
              </button>
            ) : step === 'loading-transcript' ? (
              <button className="vts-fetch-btn" disabled>
                <span className="auth-spinner" style={{ width: '13px', height: '13px', borderWidth: '2px' }} aria-hidden="true" />
                Extracting Transcript…
              </button>
            ) : step === 'idle' && hasTranscript ? (
              <button
                id="fetch-transcript-btn"
                onClick={handleFetchLanguages}
                className="vts-fetch-btn"
              >
                <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                  <path d="M21.5 2v6h-6M21.34 15.57a10 10 0 1 1-.57-8.38l5.67-5.67" />
                </svg>
                Re-fetch Transcript
              </button>
            ) : null}
          </div>
        </div>

        {/* ── Error Banner ── */}
        {error && (
          <div className="vts-error-card" role="alert">
            <svg className="vts-error-icon" width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
              <circle cx="12" cy="12" r="10" />
              <line x1="12" y1="8" x2="12" y2="12" />
              <line x1="12" y1="16" x2="12.01" y2="16" />
            </svg>
            <div className="vts-error-content">
              <strong>Error Loading Transcript</strong>
              <span>{error}</span>
              <div className="vts-error-actions">
                <button className="vts-retry-btn" onClick={handleFetchLanguages}>
                  Try Again
                </button>
                <button className="vts-dismiss-btn" onClick={() => setError('')}>
                  Dismiss
                </button>
              </div>
            </div>
          </div>
        )}

        {/* ── Loading Languages State ── */}
        {step === 'loading-languages' && (
          <div className="vts-loading-card">
            <div className="vts-loading-glow-backdrop" />

            <div className="vts-loading-hero">
              <div className="vts-icon-wrapper">
                <div className="vts-icon-pulse-ring" />
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <circle cx="12" cy="12" r="10" />
                  <line x1="2" y1="12" x2="22" y2="12" />
                  <path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z" />
                </svg>
              </div>

              <div className="vts-loading-info">
                <div className="vts-loading-title-row">
                  <span className="vts-loading-title">Checking Available Transcript Languages…</span>
                </div>
                <p className="vts-loading-desc">
                  Connecting to YouTube to retrieve available subtitles, audio tracks, and auto-generated captions.
                </p>
              </div>
            </div>

            <div className="vts-progress-container">
              <div className="vts-progress-bar-track">
                <div className="vts-progress-bar-fill" />
              </div>
              <div className="vts-progress-status-row">
                <span className="vts-progress-step-text">
                  <svg className="vts-mini-spin" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <path d="M21 12a9 9 0 1 1-6.219-8.56" />
                  </svg>
                  Querying video subtitles…
                </span>
                <span>Connecting</span>
              </div>
            </div>

            {/* Language skeleton chips preview */}
            <div className="vts-languages-skeleton-grid">
              {[1, 2, 3, 4, 5, 6].map((i) => (
                <div key={i} className="vts-language-skeleton-card vts-shimmer-effect">
                  <div className="vts-skeleton-line" style={{ width: `${60 + (i % 3) * 15}%` }} />
                  <div className="vts-skeleton-pill" />
                </div>
              ))}
            </div>
          </div>
        )}

        {/* ── Language Selection State ── */}
        {step === 'language-selection' && (
          <div className="vts-lang-selection-container">
            <LanguageSelector
              languages={languages}
              selected={selectedLang}
              onSelect={setSelectedLang}
              onConfirm={handleConfirmLanguage}
              isLoading={false}
            />
            <div className="vts-lang-selection-footer">
              <button
                id="cancel-language-selection-btn"
                onClick={handleCancel}
                className="vts-cancel-btn"
              >
                Cancel &amp; Close
              </button>
            </div>
          </div>
        )}

        {/* ── Loading Transcript State ── */}
        {step === 'loading-transcript' && (
          <div className="vts-loading-card">
            <div className="vts-loading-glow-backdrop" />

            <div className="vts-loading-hero">
              <div className="vts-icon-wrapper">
                <div className="vts-icon-pulse-ring" />
                <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                  <polyline points="14 2 14 8 20 8" />
                  <line x1="16" y1="13" x2="8" y2="13" />
                  <line x1="16" y1="17" x2="8" y2="17" />
                  <polyline points="10 9 9 9 8 9" />
                </svg>
              </div>

              <div className="vts-loading-info">
                <div className="vts-loading-title-row">
                  <span className="vts-loading-title">Extracting &amp; Syncing Transcript…</span>
                  {selectedLangLabel && (
                    <span className="vts-lang-pill">
                      <svg width="10" height="10" viewBox="0 0 24 24" fill="currentColor">
                        <circle cx="12" cy="12" r="10" />
                      </svg>
                      {selectedLangLabel}
                    </span>
                  )}
                </div>
                <p className="vts-loading-desc">
                  Downloading dialogue timestamps, parsing speech cues, and synchronizing with the video player.
                </p>
              </div>
            </div>

            {/* Flowing animated progress bar */}
            <div className="vts-progress-container">
              <div className="vts-progress-bar-track">
                <div className="vts-progress-bar-fill" />
              </div>
              <div className="vts-progress-status-row">
                <span className="vts-progress-step-text">
                  <svg className="vts-mini-spin" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2.5">
                    <path d="M21 12a9 9 0 1 1-6.219-8.56" />
                  </svg>
                  Processing timestamped dialogue cues…
                </span>
                <span>Typically takes 2–5s</span>
              </div>
            </div>

            {/* Split view skeleton preview mimicking TranscriptViewer */}
            <div className="vts-skeleton-split-preview">
              {/* Left Video Skeleton */}
              <div>
                <div className="vts-skeleton-video-box vts-shimmer-effect">
                  <div className="vts-skeleton-play-icon">
                    <svg width="20" height="20" viewBox="0 0 24 24" fill="currentColor">
                      <polygon points="5 3 19 12 5 21 5 3" />
                    </svg>
                  </div>
                </div>
                <div className="vts-skeleton-video-meta">
                  <div className="vts-skeleton-meta-item vts-shimmer-effect" style={{ width: '80px' }} />
                  <div className="vts-skeleton-meta-item vts-shimmer-effect" style={{ width: '60px' }} />
                  <div className="vts-skeleton-meta-item vts-shimmer-effect" style={{ width: '50px' }} />
                </div>
              </div>

              {/* Right Transcript Skeleton */}
              <div className="vts-skeleton-transcript-box">
                <div className="vts-skeleton-header-row">
                  <div className="vts-skeleton-line vts-shimmer-effect" style={{ width: '90px' }} />
                  <div className="vts-skeleton-line vts-shimmer-effect" style={{ width: '60px' }} />
                </div>
                <div className="vts-skeleton-search-input vts-shimmer-effect" />
                <div className="vts-skeleton-segment-rows">
                  {[85, 65, 92, 74].map((width, idx) => (
                    <div key={idx} className="vts-skeleton-segment-row vts-shimmer-effect">
                      <div className="vts-skeleton-ts" />
                      <div className="vts-skeleton-text-wrap">
                        <div className="vts-skeleton-text-line1" style={{ width: `${width}%` }} />
                        <div className="vts-skeleton-text-line2" style={{ width: `${width - 25}%` }} />
                      </div>
                    </div>
                  ))}
                </div>
              </div>
            </div>
          </div>
        )}

        {/* ── Empty State (No transcript yet & Idle) ── */}
        {!hasTranscript && step === 'idle' && (
          <div className="vts-empty-card">
            <div className="vts-empty-icon-wrap">
              <svg width="28" height="28" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.75" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M14 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V8z" />
                <polyline points="14 2 14 8 20 8" />
                <line x1="16" y1="13" x2="8" y2="13" />
                <line x1="16" y1="17" x2="8" y2="17" />
                <polyline points="10 9 9 9 8 9" />
              </svg>
            </div>
            <div>
              <h3 className="vts-empty-title">No Transcript Loaded</h3>
              <p className="vts-empty-desc">
                Fetch the dialogue transcripts and timestamps directly from YouTube to preview segments, search dialogue, and detect viral moments with Gemini AI.
              </p>
            </div>
            <button
              id="empty-fetch-transcript-btn"
              onClick={handleFetchLanguages}
              className="vts-fetch-btn vts-fetch-btn-primary"
              style={{ padding: '10px 22px', fontSize: '0.95rem' }}
            >
              <svg width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
                <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                <polyline points="7 10 12 15 17 10" />
                <line x1="12" y1="15" x2="12" y2="3" />
              </svg>
              Fetch Transcript from YouTube
            </button>
          </div>
        )}

        {/* ── Transcript Viewer — Visible when transcript exists and not busy ── */}
        {hasTranscript && !isBusy && step !== 'language-selection' && (
          <TranscriptViewer
            videoId={youtubeId}
            segments={currentSegments}
            languageCode={currentLanguageCode}
          />
        )}
      </div>
    </section>
  );
}
